### ISSUE TITLE
我用官网的decode_audio转pcm报错：[mp3float @ 0x7fed5680e400] Header missing

### ISSUE THREAD

**Issue by gleeeli** [gongluck/FFmpeg4.0-study#1]
知道什么原因吗

我就改了官网的这句：
codec = avcodec_find_decoder(AV_CODEC_ID_MP3);
然后传入两个文件路径

**Comment by gongluck** [comment]
> 
> 
> 知道什么原因吗
> 
> 我就改了官网的这句：
> codec = avcodec_find_decoder(AV_CODEC_ID_MP3);
> 然后传入两个文件路径

应该是你的输入文件包含了除了音频之外的数据，你试一下先用命令
.\ffmpeg.exe -i in.flv -acodec copy -vn in.aac
生成一个只有音频的文件再运行。

**Comment by gleeeli** [comment]
我解决了，解码Mp2没问题，解码MP3会报这个错，解析包packet的方法不支持封装格式，貌似这个原因


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: gongluck <notifications@github.com>
发送时间: 2019年6月20日 19:04
收件人: gongluck/FFmpeg4.0-study <FFmpeg4.0-study@noreply.github.com>
抄送: gleeeli <1594713312@qq.com>, Author <author@noreply.github.com>
主题: 回复：[gongluck/FFmpeg4.0-study] 我用官网的decode_audio转pcm报错：[mp3float @ 0x7fed5680e400] Header missing (#1)



 
知道什么原因吗
 
我就改了官网的这句：
 codec = avcodec_find_decoder(AV_CODEC_ID_MP3);
 然后传入两个文件路径
  
应该是你的输入文件包含了除了音频之外的数据，你试一下先用命令

**Comment by gongluck** [comment]
> 
> 我解决了，解码Mp2没问题，解码MP3会报这个错，解析包packet的方法不支持封装格式，貌似这个原因 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: gongluck <notifications@github.com> 发送时间: 2019年6月20日 19:04 收件人: gongluck/FFmpeg4.0-study <FFmpeg4.0-study@noreply.github.com> 抄送: gleeeli <1594713312@qq.com>, Author <author@noreply.github.com> 主题: 回复：[gongluck/FFmpeg4.0-study] 我用官网的decode_audio转pcm报错：[mp3float @ 0x7fed5680e400] Header missing (#1) 知道什么原因吗 我就改了官网的这句： codec = avcodec_find_decoder(AV_CODEC_ID_MP3); 然后传入两个文件路径 应该是你的输入文件包含了除了音频之外的数据，你试一下先用命令 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

[mp3float @ 0x7fed5680e400] Header missing
这个错误，就是说对于解码器，数据有问题嘛。1、可能数据不是MP3编码的；2、可能数据有杂，那个例子是把所有数据都当音频处理的。
如果你是同一个数据输入用MP2和MP3，一个成功，一个不成功，那应该就是第一个原因。
因为我调试的时候是能正常解码MP3的，就是从in.flv分离出aac作为输入。

**Comment by typenoob** [comment]
是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_ID_MP3**解码出来的是杂音。

**Comment by typenoob** [comment]
> 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_ID_MP3**解码出来的是杂音。

ubuntu24.04 apt install libavutil-dev libavcodec-dev

**Comment by gongluck** [comment]
> > 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_ID_MP3**解码出来的是杂音。
> 
> ubuntu24.04 apt install libavutil-dev libavcodec-dev

1.ffmpeg的头文件和库文件版本一致吗？
2.用分析工具看看输入文件的媒体类型？

**Comment by typenoob** [comment]
> > > 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_I> > > 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_ID_MP3**解码出来的是杂音。
> > 
> > 
> > ubuntu24.04 apt install libavutil-dev libavcodec-dev
> 
> 1.ffmpeg的头文件和库文件版本一致吗？ 2.用分析工具看看输入文件的媒体类型？

感谢回复，
1. 头文件的LIBAVCODEC_VERSION是60，库文件也是libavcodec.so.60
2. 我使用`ffmpeg -acodec mp3 -i sample.mp3 -f s16le sample.pcm`输出的是正确的内容，因此不太可能会是文件的编码不正确。
能询问一下您的使用的头文件和库文件版本以及构建和测试命令吗？

**Comment by gongluck** [comment]
> > > > 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_I> > > 是我的环境不对吗 我去除了header之后也只有设定解码器为**AV_CODEC_ID_MP2**才能正常解码mp3，如果设为**AV_CODEC_ID_MP3**解码出来的是杂音。
> 
> > > 
> 
> > > 
> 
> > > ubuntu24.04 apt install libavutil-dev libavcodec-dev
> 
> > 
> 
> > 1.ffmpeg的头文件和库文件版本一致吗？ 2.用分析工具看看输入文件的媒体类型？
> 
> 
> 
> 感谢回复，
> 
> 1. 头文件的LIBAVCODEC_VERSION是60，库文件也是libavcodec.so.60
> 
> 2. 我使用`ffmpeg -acodec mp3 -i sample.mp3 -f s16le sample.pcm`输出的是正确的内容，因此不太可能会是文件的编码不正确。
> 
> 能询问一下您的使用的头文件和库文件版本以及构建和测试命令吗？




我用的头文件和库都在这个仓库里的，inc、lib、bin这三个目录，但是是vc++的工程。构建配置也是默认的。

其实也可以对比下你使用的这个版本的samples源码和我这个仓库的有没有区别？我这个的版本应该是4.0.2的，不排除后面的版本会有差异。
